# Generated by Django 4.0.5 on 2022-07-15 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='reg_name',
            new_name='reg_num',
        ),
    ]
