# Generated by Django 4.0.5 on 2022-07-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_rename_reg_name_employee_reg_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parttimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('reg_num', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('bank', models.CharField(max_length=20)),
                ('bank_num', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('part', models.CharField(max_length=30)),
                ('inwork', models.DateField()),
                ('outwork', models.DateField()),
                ('health', models.CharField(max_length=30)),
                ('content', models.TextField()),
            ],
        ),
    ]
