# Generated by Django 4.0.5 on 2022-07-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_parttimer_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parttimer',
            name='outwork',
            field=models.DateField(blank=True, null=True),
        ),
    ]
