# Generated by Django 4.0.5 on 2022-07-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_parttimer_outwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('working', models.CharField(max_length=15)),
                ('start', models.CharField(max_length=15)),
                ('end', models.CharField(max_length=15)),
                ('extra_type', models.CharField(blank=True, max_length=10, null=True)),
                ('extra', models.IntegerField(blank=True, null=True)),
                ('dayoff', models.IntegerField()),
                ('annual', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
    ]
