# Generated by Django 4.0.3 on 2022-07-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_workemployee'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkParttimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('time', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
    ]
