# Generated by Django 4.0.3 on 2022-07-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_workoneday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oneday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('reg_name', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
            ],
        ),
    ]
