# Generated by Django 4.0.3 on 2022-07-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uploadFile',
            field=models.FileField(upload_to=''),
        ),
    ]
