# Generated by Django 4.0.3 on 2022-07-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_alter_document_uploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='outwork',
            field=models.DateField(blank=True, null=True),
        ),
    ]
