# Generated by Django 4.0.3 on 2022-08-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_laborcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='notreport',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
