# Generated by Django 4.0.3 on 2022-08-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_employee_notreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttimer',
            name='notreport',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
