# Generated by Django 4.0.3 on 2022-08-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_parttimer_notreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('worktype', models.CharField(max_length=10)),
                ('workstart', models.IntegerField()),
                ('workend', models.IntegerField()),
                ('breaktime', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
    ]
