# Generated by Django 4.0.3 on 2022-08-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_workstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstaff',
            name='breaktime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
