# Generated by Django 4.0.5 on 2022-07-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=40)),
                ('regnum', models.CharField(max_length=20)),
                ('event', models.CharField(max_length=20)),
                ('bank', models.CharField(max_length=20)),
                ('banknum', models.CharField(max_length=20)),
                ('callnum', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ClientTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('client', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('pay', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Etc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('etc', models.CharField(max_length=40)),
                ('pay', models.CharField(max_length=20)),
                ('paytype', models.CharField(max_length=20)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fix', models.CharField(max_length=50)),
                ('event', models.CharField(max_length=30)),
                ('paytype', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FixCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fix', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('pay', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rant', models.CharField(max_length=40)),
                ('landload', models.CharField(max_length=20)),
                ('bank', models.CharField(max_length=20)),
                ('banknum', models.CharField(max_length=20)),
                ('pay', models.CharField(max_length=20)),
                ('surtax', models.CharField(max_length=20)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RantPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rant', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('pay', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Royalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('royalty', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('pay', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
    ]
