# Generated by Django 4.0.5 on 2022-06-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=40)),
                ('regnum', models.CharField(max_length=20)),
                ('event', models.CharField(max_length=20)),
                ('bank', models.CharField(max_length=20)),
                ('banknum', models.CharField(max_length=20)),
                ('callnum', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
