# Generated by Django 4.0.5 on 2022-06-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('etc', models.CharField(max_length=40)),
                ('pay', models.CharField(max_length=20)),
                ('paytype', models.CharField(max_length=20)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rant', models.CharField(max_length=40)),
                ('landload', models.CharField(max_length=20)),
                ('bank', models.CharField(max_length=20)),
                ('banknum', models.CharField(max_length=20)),
                ('pay', models.CharField(max_length=20)),
                ('total', models.CharField(max_length=20)),
                ('content', models.TextField()),
            ],
        ),
    ]
