# Generated by Django 4.0.5 on 2022-07-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etc',
            name='date',
        ),
        migrations.AddField(
            model_name='etc',
            name='summary',
            field=models.CharField(default=10, max_length=50),
            preserve_default=False,
        ),
    ]
