# Generated by Django 4.0.5 on 2022-07-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_remove_etc_date_etc_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtcPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=50)),
                ('etc', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('pay', models.IntegerField()),
                ('paytype', models.CharField(max_length=20)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='etc',
            name='pay',
            field=models.IntegerField(),
        ),
    ]
