# Generated by Django 4.0.5 on 2022-06-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_rename_total_rant_surtax'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('client', models.CharField(max_length=40)),
                ('price', models.CharField(max_length=50)),
                ('pay', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
    ]
