# Generated by Django 4.0.5 on 2022-07-05 15:18

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_etcpay_alter_etc_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='etcpay',
            name='date',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
