# Generated by Django 4.0.5 on 2022-06-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_clienttrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttrade',
            name='pay',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='clienttrade',
            name='price',
            field=models.IntegerField(),
        ),
    ]
