# Generated by Django 4.0.5 on 2022-07-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_etcpay_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttrade',
            name='card',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
