# Generated by Django 4.0.5 on 2022-06-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_alter_clienttrade_pay_alter_clienttrade_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fix', models.CharField(max_length=50)),
                ('event', models.CharField(max_length=30)),
                ('paytype', models.CharField(max_length=15)),
            ],
        ),
    ]
