# Generated by Django 4.0.5 on 2022-07-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_clienttrade_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttrade',
            name='card',
            field=models.IntegerField(default=0),
        ),
    ]
