# Generated by Django 4.0.5 on 2022-06-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_fix'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fix', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('pay', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
    ]
