# Generated by Django 4.0.3 on 2022-08-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_alter_clienttrade_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('card', models.CharField(max_length=30)),
                ('cost', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
    ]
