# Generated by Django 4.0.3 on 2022-08-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_cardcost'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=30)),
                ('content', models.TextField()),
            ],
        ),
    ]
