# Generated by Django 4.0.3 on 2022-08-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0008_cardinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_card',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
